name:                haskell-brainfuck
version:             0.1.0.0
github:              "https://github.com/alkazarix/haskell-brainfuck"
license:             BSD3
author:              "alkazarix"
maintainer:          "https://github.com/alkazarix/"
copyright:           "2020 alkazarix"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alkazarix/haskell-brainfuck#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.0 && <= 3.1.14.0
- mtl >= 2.2.2

library:
  source-dirs: src

executables:
  haskell-brainfuck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-brainfuck

tests:
  haskell-brainfuck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-brainfuck
